// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJNXU26fdJ2zYrwzc6g2TRI8sgSi3mH4',
    appId: '1:53881528213:web:10737f63778c72c473209c',
    messagingSenderId: '53881528213',
    projectId: 'fir-flutter-e77e7',
    authDomain: 'fir-flutter-e77e7.firebaseapp.com',
    storageBucket: 'fir-flutter-e77e7.appspot.com',
    measurementId: 'G-QBL82N026M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmW8Zfi4p0GjvgNLnv5RAzvhaBlTb4C2Y',
    appId: '1:53881528213:android:129162f3f9bb73d373209c',
    messagingSenderId: '53881528213',
    projectId: 'fir-flutter-e77e7',
    storageBucket: 'fir-flutter-e77e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRqRoy4umRYTEeKPxwrzoo6oE48RtGLI',
    appId: '1:53881528213:ios:7f52c0b30c5853d773209c',
    messagingSenderId: '53881528213',
    projectId: 'fir-flutter-e77e7',
    storageBucket: 'fir-flutter-e77e7.appspot.com',
    iosClientId: '53881528213-2pkootfl5jlub848btgin5254jbl6b8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRqRoy4umRYTEeKPxwrzoo6oE48RtGLI',
    appId: '1:53881528213:ios:7f52c0b30c5853d773209c',
    messagingSenderId: '53881528213',
    projectId: 'fir-flutter-e77e7',
    storageBucket: 'fir-flutter-e77e7.appspot.com',
    iosClientId: '53881528213-2pkootfl5jlub848btgin5254jbl6b8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
